version: "3.1"

services:
  php:
    image: php:7.1.7-cli
    volumes:
      - .:/opt/php
      - ./docker/run.sh:/opt/php/docker/run.sh
    working_dir: /opt/php
    restart: unless-stopped
#    privileged: true
#    entrypoint: /bin/bash
#    command: ["/opt/php/docker/run.sh"]